{
 "title": "Restaurant",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Top ordered dishes",
   "type": "bargauge",
   "gridPos": { "h": 21, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT d.name, dish_ordered_number as \"Order Count\"\r\nFROM (SELECT dish_id, count(dish_id) dish_ordered_number,  DENSE_RANK() OVER (order by count(dish_id) desc) as rank FROM orders group by dish_id order by rank) as dish_popularity \r\nINNER JOIN dishes d on d.id = dish_popularity.dish_id\r\nWHERE rank <= 3 \r\norder by rank"
    }
   ]
  },
  {
   "title": "Top revenue generated dishes",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "p7" ] } },
   "targets": [
    {
     "rawSql": "select name, \"Number of Orders\", \"Number of Orders\" * price as \"Revenue by dish\" from (SELECT dish_id, COUNT(dish_id) \"Number of Orders\", DENSE_RANK() OVER(order by COUNT(dish_id) desc) from orders o GROUP BY dish_id) as dish_popularity\r\n inner join dishes d on d.id = dish_popularity.dish_id order by \"Revenue by dish\" desc "
    }
   ]
  },
  {
   "title": "Total Revenue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(price) FROM orders o inner join dishes d on d.id = o.dish_id"
    }
   ]
  }
 ]
}